baseurl: /
permalink: /:year/:month/:day/:title
name: Mockra
url: http://mockra.com
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
author:
  name: David Ratajczak
  email: david@mockra.com
gems:
  - jekyll-feed
  - jekyll-gist
